// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: events.sql

package sqlc_generated

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createEvent = `-- name: CreateEvent :one
INSERT INTO events (message_id, channel_id, creator_id, title, description, max_slots, scheduled_at, private_channel_id, questions_thread_id)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING id, message_id, channel_id, creator_id, title, description, max_slots, scheduled_at, private_channel_id, questions_thread_id, organizer_validation_dm_sent_at, organizer_step1_finalized_at, created_at, updated_at
`

type CreateEventParams struct {
	MessageID         string
	ChannelID         string
	CreatorID         string
	Title             string
	Description       string
	MaxSlots          int32
	ScheduledAt       pgtype.Timestamptz
	PrivateChannelID  string
	QuestionsThreadID string
}

func (q *Queries) CreateEvent(ctx context.Context, arg CreateEventParams) (Event, error) {
	row := q.db.QueryRow(ctx, createEvent,
		arg.MessageID,
		arg.ChannelID,
		arg.CreatorID,
		arg.Title,
		arg.Description,
		arg.MaxSlots,
		arg.ScheduledAt,
		arg.PrivateChannelID,
		arg.QuestionsThreadID,
	)
	var i Event
	err := row.Scan(
		&i.ID,
		&i.MessageID,
		&i.ChannelID,
		&i.CreatorID,
		&i.Title,
		&i.Description,
		&i.MaxSlots,
		&i.ScheduledAt,
		&i.PrivateChannelID,
		&i.QuestionsThreadID,
		&i.OrganizerValidationDmSentAt,
		&i.OrganizerStep1FinalizedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteEvent = `-- name: DeleteEvent :exec
DELETE FROM events WHERE id = $1
`

func (q *Queries) DeleteEvent(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteEvent, id)
	return err
}

const findEventsNeedingH48OrganizerDM = `-- name: FindEventsNeedingH48OrganizerDM :many
SELECT id, message_id, channel_id, creator_id, title, description, max_slots, scheduled_at, private_channel_id, questions_thread_id, organizer_validation_dm_sent_at, organizer_step1_finalized_at, created_at, updated_at FROM events
WHERE scheduled_at IS NOT NULL
  AND scheduled_at > $1
  AND scheduled_at - interval '48 hours' <= $1
  AND scheduled_at - interval '47 hours' > $1
  AND organizer_validation_dm_sent_at IS NULL
`

func (q *Queries) FindEventsNeedingH48OrganizerDM(ctx context.Context, scheduledAt pgtype.Timestamptz) ([]Event, error) {
	rows, err := q.db.Query(ctx, findEventsNeedingH48OrganizerDM, scheduledAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Event
	for rows.Next() {
		var i Event
		if err := rows.Scan(
			&i.ID,
			&i.MessageID,
			&i.ChannelID,
			&i.CreatorID,
			&i.Title,
			&i.Description,
			&i.MaxSlots,
			&i.ScheduledAt,
			&i.PrivateChannelID,
			&i.QuestionsThreadID,
			&i.OrganizerValidationDmSentAt,
			&i.OrganizerStep1FinalizedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getEventByID = `-- name: GetEventByID :one
SELECT id, message_id, channel_id, creator_id, title, description, max_slots, scheduled_at, private_channel_id, questions_thread_id, organizer_validation_dm_sent_at, organizer_step1_finalized_at, created_at, updated_at FROM events WHERE id = $1
`

func (q *Queries) GetEventByID(ctx context.Context, id int64) (Event, error) {
	row := q.db.QueryRow(ctx, getEventByID, id)
	var i Event
	err := row.Scan(
		&i.ID,
		&i.MessageID,
		&i.ChannelID,
		&i.CreatorID,
		&i.Title,
		&i.Description,
		&i.MaxSlots,
		&i.ScheduledAt,
		&i.PrivateChannelID,
		&i.QuestionsThreadID,
		&i.OrganizerValidationDmSentAt,
		&i.OrganizerStep1FinalizedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getEventByMessageID = `-- name: GetEventByMessageID :one
SELECT id, message_id, channel_id, creator_id, title, description, max_slots, scheduled_at, private_channel_id, questions_thread_id, organizer_validation_dm_sent_at, organizer_step1_finalized_at, created_at, updated_at FROM events WHERE message_id = $1
`

func (q *Queries) GetEventByMessageID(ctx context.Context, messageID string) (Event, error) {
	row := q.db.QueryRow(ctx, getEventByMessageID, messageID)
	var i Event
	err := row.Scan(
		&i.ID,
		&i.MessageID,
		&i.ChannelID,
		&i.CreatorID,
		&i.Title,
		&i.Description,
		&i.MaxSlots,
		&i.ScheduledAt,
		&i.PrivateChannelID,
		&i.QuestionsThreadID,
		&i.OrganizerValidationDmSentAt,
		&i.OrganizerStep1FinalizedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getEventByPrivateChannelID = `-- name: GetEventByPrivateChannelID :one
SELECT id, message_id, channel_id, creator_id, title, description, max_slots, scheduled_at, private_channel_id, questions_thread_id, organizer_validation_dm_sent_at, organizer_step1_finalized_at, created_at, updated_at FROM events WHERE private_channel_id = $1
`

func (q *Queries) GetEventByPrivateChannelID(ctx context.Context, privateChannelID string) (Event, error) {
	row := q.db.QueryRow(ctx, getEventByPrivateChannelID, privateChannelID)
	var i Event
	err := row.Scan(
		&i.ID,
		&i.MessageID,
		&i.ChannelID,
		&i.CreatorID,
		&i.Title,
		&i.Description,
		&i.MaxSlots,
		&i.ScheduledAt,
		&i.PrivateChannelID,
		&i.QuestionsThreadID,
		&i.OrganizerValidationDmSentAt,
		&i.OrganizerStep1FinalizedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getEventsByCreatorID = `-- name: GetEventsByCreatorID :many
SELECT id, message_id, channel_id, creator_id, title, description, max_slots, scheduled_at, private_channel_id, questions_thread_id, organizer_validation_dm_sent_at, organizer_step1_finalized_at, created_at, updated_at FROM events WHERE creator_id = $1 ORDER BY created_at DESC
`

func (q *Queries) GetEventsByCreatorID(ctx context.Context, creatorID string) ([]Event, error) {
	rows, err := q.db.Query(ctx, getEventsByCreatorID, creatorID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Event
	for rows.Next() {
		var i Event
		if err := rows.Scan(
			&i.ID,
			&i.MessageID,
			&i.ChannelID,
			&i.CreatorID,
			&i.Title,
			&i.Description,
			&i.MaxSlots,
			&i.ScheduledAt,
			&i.PrivateChannelID,
			&i.QuestionsThreadID,
			&i.OrganizerValidationDmSentAt,
			&i.OrganizerStep1FinalizedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markOrganizerStep1Finalized = `-- name: MarkOrganizerStep1Finalized :exec
UPDATE events SET organizer_step1_finalized_at = NOW(), updated_at = NOW() WHERE id = $1
`

func (q *Queries) MarkOrganizerStep1Finalized(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, markOrganizerStep1Finalized, id)
	return err
}

const markOrganizerValidationDMSent = `-- name: MarkOrganizerValidationDMSent :exec
UPDATE events SET organizer_validation_dm_sent_at = NOW(), updated_at = NOW() WHERE id = $1
`

func (q *Queries) MarkOrganizerValidationDMSent(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, markOrganizerValidationDMSent, id)
	return err
}

const updateEvent = `-- name: UpdateEvent :exec
UPDATE events SET
    title = $2,
    description = $3,
    max_slots = $4,
    scheduled_at = $5,
    updated_at = NOW()
WHERE id = $1
`

type UpdateEventParams struct {
	ID          int64
	Title       string
	Description string
	MaxSlots    int32
	ScheduledAt pgtype.Timestamptz
}

func (q *Queries) UpdateEvent(ctx context.Context, arg UpdateEventParams) error {
	_, err := q.db.Exec(ctx, updateEvent,
		arg.ID,
		arg.Title,
		arg.Description,
		arg.MaxSlots,
		arg.ScheduledAt,
	)
	return err
}
