// Code generated by sqlc. DO NOT EDIT.
// Run sqlc generate to regenerate.

package sqlc_generated

import (
	"context"
)

const createEvent = `-- name: CreateEvent :one
INSERT INTO events (message_id, channel_id, creator_id, title, description, max_slots)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, message_id, channel_id, creator_id, title, description, max_slots, created_at, updated_at
`

func (q *Queries) CreateEvent(ctx context.Context, arg CreateEventParams) (Event, error) {
	row := q.db.QueryRow(ctx, createEvent,
		arg.MessageID, arg.ChannelID, arg.CreatorID, arg.Title, arg.Description, arg.MaxSlots,
	)
	var e Event
	err := row.Scan(
		&e.ID, &e.MessageID, &e.ChannelID, &e.CreatorID, &e.Title, &e.Description, &e.MaxSlots,
		&e.CreatedAt, &e.UpdatedAt,
	)
	return e, err
}

const getEventByMessageID = `-- name: GetEventByMessageID :one
SELECT id, message_id, channel_id, creator_id, title, description, max_slots, created_at, updated_at FROM events WHERE message_id = $1
`

func (q *Queries) GetEventByMessageID(ctx context.Context, messageID string) (Event, error) {
	row := q.db.QueryRow(ctx, getEventByMessageID, messageID)
	var e Event
	err := row.Scan(
		&e.ID, &e.MessageID, &e.ChannelID, &e.CreatorID, &e.Title, &e.Description, &e.MaxSlots,
		&e.CreatedAt, &e.UpdatedAt,
	)
	return e, err
}

const getEventByID = `-- name: GetEventByID :one
SELECT id, message_id, channel_id, creator_id, title, description, max_slots, created_at, updated_at FROM events WHERE id = $1
`

func (q *Queries) GetEventByID(ctx context.Context, id int64) (Event, error) {
	row := q.db.QueryRow(ctx, getEventByID, id)
	var e Event
	err := row.Scan(
		&e.ID, &e.MessageID, &e.ChannelID, &e.CreatorID, &e.Title, &e.Description, &e.MaxSlots,
		&e.CreatedAt, &e.UpdatedAt,
	)
	return e, err
}

const getEventsByCreatorID = `-- name: GetEventsByCreatorID :many
SELECT id, message_id, channel_id, creator_id, title, description, max_slots, created_at, updated_at FROM events WHERE creator_id = $1 ORDER BY created_at DESC
`

func (q *Queries) GetEventsByCreatorID(ctx context.Context, creatorID string) ([]Event, error) {
	rows, err := q.db.Query(ctx, getEventsByCreatorID, creatorID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Event
	for rows.Next() {
		var i Event
		if err := rows.Scan(
			&i.ID, &i.MessageID, &i.ChannelID, &i.CreatorID, &i.Title, &i.Description, &i.MaxSlots,
			&i.CreatedAt, &i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateEvent = `-- name: UpdateEvent :exec
UPDATE events SET title = $2, description = $3, max_slots = $4, updated_at = NOW() WHERE id = $1
`

func (q *Queries) UpdateEvent(ctx context.Context, arg UpdateEventParams) error {
	_, err := q.db.Exec(ctx, updateEvent, arg.ID, arg.Title, arg.Description, arg.MaxSlots)
	return err
}

const deleteEvent = `-- name: DeleteEvent :exec
DELETE FROM events WHERE id = $1
`

func (q *Queries) DeleteEvent(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteEvent, id)
	return err
}

type CreateEventParams struct {
	MessageID   string
	ChannelID   string
	CreatorID   string
	Title       string
	Description string
	MaxSlots    int32
}

type UpdateEventParams struct {
	ID          int64
	Title       string
	Description string
	MaxSlots    int32
}
