// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc_generated

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Event struct {
	ID                          int64
	MessageID                   string
	ChannelID                   string
	CreatorID                   string
	Title                       string
	Description                 string
	MaxSlots                    int32
	ScheduledAt                 pgtype.Timestamptz
	PrivateChannelID            string
	QuestionsThreadID           string
	OrganizerValidationDmSentAt pgtype.Timestamptz
	OrganizerStep1FinalizedAt   pgtype.Timestamptz
	CreatedAt                   pgtype.Timestamptz
	UpdatedAt                   pgtype.Timestamptz
}

type Participant struct {
	ID        int64
	EventID   int64
	UserID    string
	Username  string
	Status    string
	JoinedAt  pgtype.Timestamptz
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}
