// Code generated by sqlc. DO NOT EDIT.
// Run sqlc generate to regenerate.

package sqlc_generated

import "time"

type Event struct {
	ID          int64
	MessageID   string
	ChannelID   string
	CreatorID   string
	Title       string
	Description string
	MaxSlots    int32
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

type Participant struct {
	ID        int64
	EventID   int64
	UserID    string
	Username  string
	Status    string
	JoinedAt  time.Time
	CreatedAt time.Time
	UpdatedAt time.Time
}
