// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: participants.sql

package sqlc_generated

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countParticipantsByEventIDAndStatus = `-- name: CountParticipantsByEventIDAndStatus :one
SELECT COUNT(*) FROM participants WHERE event_id = $1 AND status = $2
`

type CountParticipantsByEventIDAndStatusParams struct {
	EventID int64
	Status  string
}

func (q *Queries) CountParticipantsByEventIDAndStatus(ctx context.Context, arg CountParticipantsByEventIDAndStatusParams) (int64, error) {
	row := q.db.QueryRow(ctx, countParticipantsByEventIDAndStatus, arg.EventID, arg.Status)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createParticipant = `-- name: CreateParticipant :one
INSERT INTO participants (event_id, user_id, username, status, joined_at)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, event_id, user_id, username, status, joined_at, created_at, updated_at
`

type CreateParticipantParams struct {
	EventID  int64
	UserID   string
	Username string
	Status   string
	JoinedAt pgtype.Timestamptz
}

func (q *Queries) CreateParticipant(ctx context.Context, arg CreateParticipantParams) (Participant, error) {
	row := q.db.QueryRow(ctx, createParticipant,
		arg.EventID,
		arg.UserID,
		arg.Username,
		arg.Status,
		arg.JoinedAt,
	)
	var i Participant
	err := row.Scan(
		&i.ID,
		&i.EventID,
		&i.UserID,
		&i.Username,
		&i.Status,
		&i.JoinedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteParticipant = `-- name: DeleteParticipant :exec
DELETE FROM participants WHERE id = $1
`

func (q *Queries) DeleteParticipant(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteParticipant, id)
	return err
}

const getParticipantByEventIDAndUserID = `-- name: GetParticipantByEventIDAndUserID :one
SELECT id, event_id, user_id, username, status, joined_at, created_at, updated_at FROM participants WHERE event_id = $1 AND user_id = $2
`

type GetParticipantByEventIDAndUserIDParams struct {
	EventID int64
	UserID  string
}

func (q *Queries) GetParticipantByEventIDAndUserID(ctx context.Context, arg GetParticipantByEventIDAndUserIDParams) (Participant, error) {
	row := q.db.QueryRow(ctx, getParticipantByEventIDAndUserID, arg.EventID, arg.UserID)
	var i Participant
	err := row.Scan(
		&i.ID,
		&i.EventID,
		&i.UserID,
		&i.Username,
		&i.Status,
		&i.JoinedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getParticipantByID = `-- name: GetParticipantByID :one
SELECT id, event_id, user_id, username, status, joined_at, created_at, updated_at FROM participants WHERE id = $1
`

func (q *Queries) GetParticipantByID(ctx context.Context, id int64) (Participant, error) {
	row := q.db.QueryRow(ctx, getParticipantByID, id)
	var i Participant
	err := row.Scan(
		&i.ID,
		&i.EventID,
		&i.UserID,
		&i.Username,
		&i.Status,
		&i.JoinedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getParticipantsByEventID = `-- name: GetParticipantsByEventID :many
SELECT id, event_id, user_id, username, status, joined_at, created_at, updated_at FROM participants WHERE event_id = $1 ORDER BY created_at ASC
`

func (q *Queries) GetParticipantsByEventID(ctx context.Context, eventID int64) ([]Participant, error) {
	rows, err := q.db.Query(ctx, getParticipantsByEventID, eventID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Participant
	for rows.Next() {
		var i Participant
		if err := rows.Scan(
			&i.ID,
			&i.EventID,
			&i.UserID,
			&i.Username,
			&i.Status,
			&i.JoinedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getParticipantsByEventIDAndStatus = `-- name: GetParticipantsByEventIDAndStatus :many
SELECT id, event_id, user_id, username, status, joined_at, created_at, updated_at FROM participants WHERE event_id = $1 AND status = $2 ORDER BY created_at ASC
`

type GetParticipantsByEventIDAndStatusParams struct {
	EventID int64
	Status  string
}

func (q *Queries) GetParticipantsByEventIDAndStatus(ctx context.Context, arg GetParticipantsByEventIDAndStatusParams) ([]Participant, error) {
	rows, err := q.db.Query(ctx, getParticipantsByEventIDAndStatus, arg.EventID, arg.Status)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Participant
	for rows.Next() {
		var i Participant
		if err := rows.Scan(
			&i.ID,
			&i.EventID,
			&i.UserID,
			&i.Username,
			&i.Status,
			&i.JoinedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateParticipant = `-- name: UpdateParticipant :exec
UPDATE participants SET
    username = $2,
    status = $3,
    updated_at = NOW()
WHERE id = $1
`

type UpdateParticipantParams struct {
	ID       int64
	Username string
	Status   string
}

func (q *Queries) UpdateParticipant(ctx context.Context, arg UpdateParticipantParams) error {
	_, err := q.db.Exec(ctx, updateParticipant, arg.ID, arg.Username, arg.Status)
	return err
}
