// Code generated by sqlc. DO NOT EDIT.
// Run sqlc generate to regenerate.

package sqlc_generated

import (
	"context"
	"time"
)

const createParticipant = `-- name: CreateParticipant :one
INSERT INTO participants (event_id, user_id, username, status, joined_at)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, event_id, user_id, username, status, joined_at, created_at, updated_at
`

func (q *Queries) CreateParticipant(ctx context.Context, arg CreateParticipantParams) (Participant, error) {
	row := q.db.QueryRow(ctx, createParticipant,
		arg.EventID, arg.UserID, arg.Username, arg.Status, arg.JoinedAt,
	)
	var i Participant
	err := row.Scan(
		&i.ID, &i.EventID, &i.UserID, &i.Username, &i.Status, &i.JoinedAt,
		&i.CreatedAt, &i.UpdatedAt,
	)
	return i, err
}

const getParticipantByID = `-- name: GetParticipantByID :one
SELECT id, event_id, user_id, username, status, joined_at, created_at, updated_at FROM participants WHERE id = $1
`

func (q *Queries) GetParticipantByID(ctx context.Context, id int64) (Participant, error) {
	row := q.db.QueryRow(ctx, getParticipantByID, id)
	var i Participant
	err := row.Scan(
		&i.ID, &i.EventID, &i.UserID, &i.Username, &i.Status, &i.JoinedAt,
		&i.CreatedAt, &i.UpdatedAt,
	)
	return i, err
}

const getParticipantsByEventID = `-- name: GetParticipantsByEventID :many
SELECT id, event_id, user_id, username, status, joined_at, created_at, updated_at FROM participants WHERE event_id = $1 ORDER BY created_at ASC
`

func (q *Queries) GetParticipantsByEventID(ctx context.Context, eventID int64) ([]Participant, error) {
	rows, err := q.db.Query(ctx, getParticipantsByEventID, eventID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Participant
	for rows.Next() {
		var i Participant
		if err := rows.Scan(
			&i.ID, &i.EventID, &i.UserID, &i.Username, &i.Status, &i.JoinedAt,
			&i.CreatedAt, &i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	return items, rows.Err()
}

const getParticipantByEventIDAndUserID = `-- name: GetParticipantByEventIDAndUserID :one
SELECT id, event_id, user_id, username, status, joined_at, created_at, updated_at FROM participants WHERE event_id = $1 AND user_id = $2
`

func (q *Queries) GetParticipantByEventIDAndUserID(ctx context.Context, eventID int64, userID string) (Participant, error) {
	row := q.db.QueryRow(ctx, getParticipantByEventIDAndUserID, eventID, userID)
	var i Participant
	err := row.Scan(
		&i.ID, &i.EventID, &i.UserID, &i.Username, &i.Status, &i.JoinedAt,
		&i.CreatedAt, &i.UpdatedAt,
	)
	return i, err
}

const getParticipantsByEventIDAndStatus = `-- name: GetParticipantsByEventIDAndStatus :many
SELECT id, event_id, user_id, username, status, joined_at, created_at, updated_at FROM participants WHERE event_id = $1 AND status = $2 ORDER BY created_at ASC
`

func (q *Queries) GetParticipantsByEventIDAndStatus(ctx context.Context, eventID int64, status string) ([]Participant, error) {
	rows, err := q.db.Query(ctx, getParticipantsByEventIDAndStatus, eventID, status)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Participant
	for rows.Next() {
		var i Participant
		if err := rows.Scan(
			&i.ID, &i.EventID, &i.UserID, &i.Username, &i.Status, &i.JoinedAt,
			&i.CreatedAt, &i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	return items, rows.Err()
}

const updateParticipant = `-- name: UpdateParticipant :exec
UPDATE participants SET username = $2, status = $3, updated_at = NOW() WHERE id = $1
`

func (q *Queries) UpdateParticipant(ctx context.Context, arg UpdateParticipantParams) error {
	_, err := q.db.Exec(ctx, updateParticipant, arg.ID, arg.Username, arg.Status)
	return err
}

const deleteParticipant = `-- name: DeleteParticipant :exec
DELETE FROM participants WHERE id = $1
`

func (q *Queries) DeleteParticipant(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteParticipant, id)
	return err
}

const countParticipantsByEventIDAndStatus = `-- name: CountParticipantsByEventIDAndStatus :one
SELECT COUNT(*) FROM participants WHERE event_id = $1 AND status = $2
`

func (q *Queries) CountParticipantsByEventIDAndStatus(ctx context.Context, eventID int64, status string) (int64, error) {
	row := q.db.QueryRow(ctx, countParticipantsByEventIDAndStatus, eventID, status)
	var count int64
	err := row.Scan(&count)
	return count, err
}

type CreateParticipantParams struct {
	EventID   int64
	UserID    string
	Username  string
	Status    string
	JoinedAt  time.Time
}

type UpdateParticipantParams struct {
	ID       int64
	Username string
	Status   string
}
